# -*- coding: utf-8 -*-
__author__ = 'dontsov'

import os
from fxpxml import generator
import argparse


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description='FinalCutProjectGenerator')
    parser.add_argument('-k', '--keylog', default='debug.txt', help='TXT file with switch slides timestamps (generated by PresentationLogger.exe)')
    parser.add_argument('-o', '--output', default='test.fcpxml', help='Output FCPXML 1.4 file path')
    parser.add_argument('-s', '--slides', default=os.path.join(os.getcwd(), 'examples', 'presentation'), help='Folder with presentation JPG files')

    parser.add_argument('-w', '--width', type=int, default=1920, help='FC project width, pixels')
    parser.add_argument('-t', '--height', type=int, default=1080, help='FC project height, pixels')
    parser.add_argument('-m', '--frames', type=int, default=30, help='Frames per second in FC project')
    parser.add_argument('-e', '--event', default='present_event', help='FC event name')
    parser.add_argument('-n', '--name', default='present_proj', help='FC project name')

    parser.add_argument('-f', '--first_sec', type=int, default=10, help='First slide show length, seconds')
    parser.add_argument('-l', '--last_sec', type=int, default=10, help='Last slide show length, seconds')
    parser.add_argument('-g', '--gap_sec', type=int, default=0, help='Black screen before slides, seconds')
    kwargs = vars(parser.parse_args())

    for k, v in kwargs.iteritems():
        print ' - {0}: {1}'.format(k,v)
    generator(**kwargs)